language: php
sudo: required
dist: xenial
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3snapshot

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

addons:
  apt:
    packages:
    - libzip4

cache: vendor

script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist
  - ./bin/sabre-cs-fixer fix --dry-run --diff lib/

before_script: composer install --dev
